### ISSUE TITLE
EyeLink eye tracker filter problem

### ISSUE THREAD

**Issue by BenInglis** [Brain-Imaging-Center/Peripherals#2]
We've burned out the third filter for the EyeLink, causing RF interference caught by Miguel in routine QA this morning. Rick spotted that the power strip supplying all the EyeLink devices had been left on, against the label on the device, and so we can't know whether it was the continuous power or the power cycling that killed the latest filter. We were able to determine that having the EyeLink powered off removes the source of the RFI, so the burned out filter isn't a big deal if the EyeLink is kept unplugged. 

Still, for now the EyeLink cable on the filter panel has been disconnected in case someone accidentally or intentionally powers up the EyeLink. We'll leave the cable disconnected until we can work out what new filtering to implement, and what the procedure should be re. continuous power vs powering up for use and shutting down afterwards.

**Comment by BenInglis** [comment]
Rick's latest tests, summary results below, suggest that the eye tracker camera is responsible for generating the RF frequencies being picked up in the failed RF noise tests. Whether this RFI was responsible for the defective filters we can only guess, but what is clear is that the EyeLink filter isn't capable of cleaning up the camera line. The next step is probably to contact EyeLink and find out what their experience has been re. filtering their camera.

---

Here is my latest testing using the EyeLink supplied filter.

Power on.
1.  connected to filter / pass
2.  filter to cable not connected to camera & LED / pass
3.  camera / 20 kHz
4.camera & LED / -190, 20 kHz

Power on at magnet face.
1.  connected to the filter / pass
2.  cable not connected to camera & LED / pass
3.  camera / -190, -80, 230 kHz
4.  camera & LED / -190, -80, 20, 130, 230 kHz
5.  LED / pass
6.  LED / pass
7.  camera & LED / -190, 20, 230 kHz
8.  camera / -190, -80, 20, 230 kHz

**Comment by BenInglis** [comment]
Still failing RF Noise Check, the camera is still implicated:

---

Hi Marcus,

Well I ran the tests over again today and the camera is still putting out RF.  The illuminator is clean.  Swapping the input power didn't make any difference.  

Cheers,

Rick

On Fri, May 8, 2015 at 2:26 PM, Marcus Johnson marcus@sr-research.com wrote:

```
Hi Rick,

One more quick test -- can you try switching which of the two lemo connectors on the power cable goes to the camera and see if that makes a difference in the noise (switch which lemo connector goes to it).

That will hopefully be the last test.

Thanks,

Marcus

On Fri, May 8, 2015 at 5:11 PM, Richard L. REDFERN <redbush@berkeley.edu> wrote:

    Hi Marcus,

    In summary, connected through any of the filters, whether your 9 pin, my 9 pin, or BNC's ( 15 mHz & 100mHz filters), with the cables not connected to either the camera or illuminator, with or without power applied, there is no RF noise.  Once cables are connected to the devises we do see RF noise.  With this series of tests I first connected only the camera, then only the illuminator and finally both being connected.  And it makes no difference as to the location, in the corner of the room or directly at the face of the magnet where it would be used RF is the same.  I was a little surprised that on my last bank of tests the illuminator only actually did come out clean which was with your 9 pin filter.

    Cheers!

    Rick
```

**Comment by BenInglis** [comment]
New tests from Marcus Johnson at SRI.

---

Hi Rick and Ben,

We are going to send you the following pieces of equipment:
1. a battery box and lemo-lemo cable with charger
2. one P19 power cable - the whole cable including power supply and line filter
3. one 890 nm long range illuminator
4. long range camera head

Please try to do the following tests:

1) Replace the camera head you are using with the one that we send and see if that resolves the issue.  We will also either be sending you an SCD file (either on a CD file or via a separate email).  In order to test the new camera head you will need to use the File Manager to copy the SCD file to the \elcl\scd folder on the Host PC.  Here’s how:

a) Exit to the File Manager by pressing Ctrl-Alt-Q when the Host application is running.
b) On the Display PC open a browser and type 100.1.1.1 in the address bar.  This will give you access to the Host PC file manager from the Display PC.  Use the upload button to upload the file to the \elcl\scd folder.

2) If the camera head does not resolve the issue then go back to your original camera head and try the replacement P19 power cable (it is similar to the power cable you currently have).  Make sure to use all the new components).

3) If the camera head and power cable do not resolve the issue then go back to your original camera head and use the batter to power the camera and illuminator.  Make sure to use turn the batter On using its switch.  The battery just connects to the camera and illuminator via a cable that has lemo connectors on both ends.  The batter can go in the MRI scanner room (it is safe).

4) If that doesn’t resolve things then please try the different illuminator we send you.

Please let us know how this goes.  Once we isolate the problem we will need you to ship back the parts that are not needed to be replaced and the part that was the source of the issue.  We will cover shipping both ways.  Once we know the parts that need to be sent back we will send shipping documents to you so that you can use our FedEx account to send things back.

Thanks, and apologies for the inconvenience of all of this.

Marcus

**Comment by RickRedfern** [comment]
Hi Marcus,

I received the bits today.  I won't be able to get on the magnet until next
Tuesday morning and should have data about 10:00am my time.

Cheers!

Rick

**Comment by RickRedfern** [comment]
Hi Marcus,

I haven't received the SCD file.

Cheers!

Rick

**Comment by BenInglis** [comment]
Looks like the noise could be in the cable between the camera and the filter on the penetration panel. Rick's tests, below, in an email to EyeLink:

---

We ran a series yesterday afternoon with all combinations of our camera and illuminator and the units you sent while being powered by the battery and didn't find any spikes.  This morning we just ran a series with the old and new cables from the pin panel to the camera/illuminator.  We ran the test two times with the old cable with several spikes each time.  We then switched to the new cable, ran it two times, with no spikes.  One last time with the old cable and the spikes returned.  Seems that we have located the problem.

**Comment by BenInglis** [comment]
The new cable has removed the RFI and all RF checks are clean. Have requested that EyeLink performs an autopsy on the cable to try to determine the reason for the RF collection. But for now the EyeLink can be returned to routine use.

**Comment by RickRedfern** [comment]
The Eye Link is back in service.  We now have the replacement for the faulty cable installed.  I have ordered a battery backup unit for the system that can be used to power up the camera and illuminator without having to run power through the penetration panel thereby eliminating one possible source of RF ( the faulty cable).  Whether we use this full time or not remains to be seen but it will be available for immediate backup.   

As for the 32 channel coil lighting, I have come up with an IR fiber optic setup to replace the IR LED's that I initially used.  This will totally eliminate potential RF noise from the light source in the bore.  Miguel and I just tested it and Eye Link has no problem tracking though the visual light intensity one sees on the monitor may not be as bright as you think it should or needs to be.

If you would like to begin using the Eye Link please contact Miguel or me, we simply would like to know who is using it.
